# Generated by Django 3.2.9 on 2022-01-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='description',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
