# Generated by Django 3.2.9 on 2021-12-07 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='authuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='authuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='password',
            field=models.CharField(default='', max_length=128, null=True, verbose_name='password'),
        ),
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=None, max_length=64, null=True, unique=True)),
                ('expires_at', models.DateTimeField(default=users.models.get_expires_at)),
                ('activated_at', models.DateTimeField(default=None, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
