# Generated by Django 3.2.9 on 2022-01-05 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='price',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='quantity',
        ),
    ]
